### PR TITLE
Mount names that are suffixed with a slash don't have their specs loaded correctly.

### PR DESCRIPTION
**Pull request by dgreene-r7**
This PR fixes an issue where mount names that have a slash at the end have their specs loaded with double slashes (e.g. `transit//decrypt/:id`).

### CODE REVIEW

**Review by kenjones-cisco — APPROVED** [review]
LGTM

**Comment by kenjones-cisco** [comment]
Actually, just looked at the test (not sure why Travis doesn't indicate the error) but there are now 2 new errors showing up:

```
  2) pki #getConfigUrls should resolve when all required and valid inputs provided:
     AssertionError: expected { Object (name, statusCode, ...) } to be undefined
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at null.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:286:25)
      at Object.defineProperty.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at tests/backends/pki.js:385:26
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:687:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:138:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)

3) internal state #syncMounts sync up mounts:
     AssertionError: expected { Object (defaults, name, ...) } to be undefined
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at null.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:286:25)
      at Object.defineProperty.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at Context.<anonymous> (tests/internal.js:37:64)
      at Vaulted.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:138:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by dgreene-r7** [comment]
That `#getConfigUrls` test failure seems like a transient issue. See https://travis-ci.org/chiefy/vaulted/builds/163178352, https://travis-ci.org/chiefy/vaulted/builds/163207185, https://travis-ci.org/chiefy/vaulted/builds/164648974, and https://travis-ci.org/chiefy/vaulted/builds/164769905.

I'll look into the other failure.

**Review by kenjones-cisco — CHANGES_REQUESTED** [review]
The only test case was `sync up mounts` which is now tested on every single call to `prepare`. Instead of leaving it empty as such. Go ahead and delete the file all together.

`tests/internal.js`

**Review by kenjones-cisco — APPROVED** [review]

**Pull request merged**
